coverage:
  status:
    project:
      default:
        # This is an arbitrary number.
        # It is always not possible to write tests
        # for Drupal code (Plugins, Interfaces, etc.)
        target: 30%
        threshold: null
      apps:
        paths:
          - profiles/contrib/openscholar/modules/apps
        target: 30%
        threshold: null
      cp:
        paths:
          - profiles/contrib/openscholar/modules/cp
        target: 30%
        threshold: null
      custom:
        paths:
          - profiles/contrib/openscholar/modules/custom
        target: 30%
        threshold: null
      os:
        paths:
          - profiles/contrib/openscholar/modules/os
        target: 30%
        threshold: null
      vsite:
        paths:
          - profiles/contrib/openscholar/modules/vsite
        target: 30%
        threshold: null
    # It is always not possible to write tests
    # for Drupal code (Plugins, Interfaces, etc.)
    patch: false
