language: php
dist: trusty
sudo: false

cache:
  directories:
    - $HOME/.composer/cache/files
addons:
  artifacts:
    s3_region: $ARTIFACTS_S3_REGION
    paths:
      - ./web/sites/default/files

services:
  - docker

php:
  - 7.2

env:
  global:
    - DRUPAL_BASE_URL="http://127.0.0.1:8080"
    - PATH="$PATH:$HOME/.composer/vendor/bin"
  matrix:
    - JOB=job:check-coding-standards
    - JOB=job:run-unit-tests
    - JOB=job:run-kernel-tests
    - JOB=job:run-functional-tests
    - JOB=job:run-functional-javascript-tests
#    - JOB=job:run-behat-tests

before_install:
  - echo 'sendmail_path = /bin/true' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini

install:
  - composer global require consolidation/robo

before_script:
  - cp .travis/RoboFile.php .

script:
  - robo $JOB

after_success:
  - bash <(curl -s https://codecov.io/bash)
